services:
  postgres:
    image: postgres:15
    container_name: beauty_salon_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - beauty-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    container_name: beauty_salon_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    networks:
      - beauty-network

networks:
  beauty-network:
    driver: bridge
